export const PRIMARY = {
  BUTTON: {
    DEFAULT: { COLOR: "#fff", BACKGROUND: "#6542f1" },
    HOVER: { COLOR: "#fff", BACKGROUND: "#9982F4" },
    PRESSED: { COLOR: "#fff", BACKGROUND: "#4B31B0" },
    DISABLED: { COLOR: "#D0DCDC", BACKGROUND: "#EDEDED" },
  },
};
export const SECONDARY = {
  BUTTON: {
    DEFAULT: { COLOR: "#3A3A3A", BACKGROUND: "#DEDEDE" },
    HOVER: { COLOR: "#3A3A3A", BACKGROUND: "#F3F3F3" },
    PRESSED: { COLOR: "#3A3A3A", BACKGROUND: "#B8B7B9" },
    DISABLED: { COLOR: "#D0DCDC", BACKGROUND: "#EDEDED" },
  },
};
export const TERTIARY = {
  BUTTON: {
    DEFAULT: { COLOR: "#6542F1", BACKGROUND: "#fff", BORDER: "#6542F1" },
    HOVER: { COLOR: "#9982F4", BACKGROUND: "#fff", BORDER: "#9982F4" },
    PRESSED: { COLOR: "#4B31B0", BACKGROUND: "#F0EDFC", BORDER: "#4B31B0" },
    DISABLED: { COLOR: "#D0DCDC", BACKGROUND: "#EDEDED", BORDER: "#EDEDED" },
  },
};
